<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dotnet-DiscordGitHubBridge-e9d9af71-1f4b-4f72-8a55-0b81be911860</UserSecretsId>
    <RootNamespace>DiscordGitHubBridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DiscordGitHubBridge.Tests" />
  </ItemGroup>

</Project>
