<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- NU1507: multiple package sources with CPM and no source mapping -->
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
</Project>
