global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Shapes;
global using Windows.UI;
global using ColorHelper = Microsoft.UI.ColorHelper;
global using ClaudeDash.Models;
global using ClaudeDash.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using System.Text.Json;
global using ClaudeDash.Models.Timeline;
global using ClaudeDash.Models.Search;
global using ClaudeDash.Models.Remediation;
global using ClaudeDash.Models.Chat;
global using Uno.Extensions.Reactive;
global using Uno.Extensions.Navigation;
