// <auto-generated />
using DiscordGitHubBridge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordGitHubBridge.Data.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    [Migration("20260917021152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DiscordGitHubBridge.Mapping.ThreadIssueMapping", b =>
                {
                    b.Property<long>("DiscordThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubIssueUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordThreadId");

                    b.HasIndex("Status");

                    b.ToTable("ThreadIssueMappings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
